<?php

namespace Wing5wong\KamarDirectoryServices\DirectoryService;

class StudentData
{
    public function __construct(
        public string $student_id,
        public string $uuid,
        public string $role = "Student",
        public int $schoolindex,
        public string $nsn,
        public string $created,
        public string $uniqueid,
        public bool $accountdisabled,
        public bool $signedagreement,
        public string $byodinfo,
        public string $username,
        public string $firstname,
        public string $lastname,
        public string $gender,
        public string $genderpreferred,
        public string $gendercode,
        public string $ethnicityL1,
        public string $ethnicityL2,
        public array $ethnicity,
        public array $iwi,
        public string $siblinglink,
        public bool $boarder,
        public string $datebirth,
        public int $yearlevel,
        public int $fundinglevel,
        public string $moetype,
        public string $ece,
        public string $ors,
        public bool $esol,
        public string $languagespoken,
        public string $tutor,
        public string $house,
        public string $whanau,
        public array $timetabletop,
        public array $timetablebottom,
        public string $photocoperid,
        public string $startschooldate,
        public string $startingdate,
        public string $leavingdate,
        public string $leavingreason,
        public string $leavingactivity,
        public array $leavingschools,
        public string $email,
        public string $mobile,
        public bool $networkaccess,
        public string $althomedrive,
        public string $altdescription,
        public array $residences,
        public array $caregivers,
        public array $groups,
        public array $awards,
        public array $datasharing,
    ) {}
}
