<?php

namespace Wing5wong\KamarDirectoryServices\DirectoryService;

class StudentData
{
    public function __construct(
        public string $student_id,
        public ?string $uuid,
        public string $role = "Student",
        public ?int $schoolindex,
        public ?string $nsn,
        public ?string $created,
        public ?string $uniqueid,
        public ?bool $accountdisabled,
        public ?bool $signedagreement,
        public ?string $byodinfo,
        public ?string $username,
        public ?string $firstname,
        public ?string $lastname,
        public ?string $gender,
        public ?string $genderpreferred,
        public ?string $gendercode,
        public ?string $ethnicityL1,
        public ?string $ethnicityL2,
        public ?array $ethnicity,
        public ?array $iwi,
        public ?string $siblinglink,
        public ?bool $boarder,
        public ?string $datebirth,
        public ?int $yearlevel,
        public ?int $fundinglevel,
        public ?string $moetype,
        public ?string $ece,
        public ?string $ors,
        public ?bool $esol,
        public ?string $languagespoken,
        public ?string $tutor,
        public ?string $house,
        public ?string $whanau,
        public ?array $timetabletop,
        public ?array $timetablebottom,
        public ?string $photocoperid,
        public ?string $startschooldate,
        public ?string $startingdate,
        public ?string $leavingdate,
        public ?string $leavingreason,
        public ?string $leavingactivity,
        public ?array $leavingschools,
        public ?string $email,
        public ?string $mobile,
        public ?bool $networkaccess,
        public ?string $althomedrive,
        public ?string $altdescription,
        public ?array $residence,
        public ?array $caregivers,
        public ?array $groups,
        public ?array $awards,
        public ?array $datasharing,
    ) {}

    public static function fromArray($data): self
    {
        return new self(
            $data['id'],
            $data['uuid'] ?? null,
            $data['role'] = "Student",
            $data['schoolindex']  ?? null,
            $data['nsn']  ?? null,
            $data['created']  ?? null,
            $data['uniqueid']  ?? null,
            $data['accountdisabled']  ?? null,
            $data['signedagreement']  ?? null,
            $data['byodinfo']  ?? null,
            $data['username']  ?? null,
            $data['firstname']  ?? null,
            $data['lastname']  ?? null,
            $data['gender']  ?? null,
            $data['genderpreferred']  ?? null,
            $data['gendercode']  ?? null,
            $data['ethnicityL1']  ?? null,
            $data['ethnicityL2']  ?? null,
            $data['ethnicity']  ?? null,
            $data['iwi']  ?? null,
            $data['siblinglink']  ?? null,
            $data['boarder']  ?? null,
            $data['datebirth']  ?? null,
            $data['yearlevel']  ?? null,
            $data['fundinglevel']  ?? null,
            $data['moetype']  ?? null,
            $data['ece']  ?? null,
            $data['ors']  ?? null,
            $data['esol']  ?? null,
            $data['languagespoken']  ?? null,
            $data['tutor']  ?? null,
            $data['house']  ?? null,
            $data['whanau']  ?? null,
            $data['timetabletop']  ?? null,
            $data['timetablebottom']  ?? null,
            $data['photocoperid']  ?? null,
            $data['startschooldate']  ?? null,
            $data['startingdate']  ?? null,
            $data['leavingdate']  ?? null,
            $data['leavingreason']  ?? null,
            $data['leavingactivity']  ?? null,
            $data['leavingschools']  ?? null,
            $data['email']  ?? null,
            $data['mobile']  ?? null,
            $data['networkaccess']  ?? null,
            $data['althomedrive']  ?? null,
            $data['altdescription']  ?? null,
            $data['residence']  ?? null,
            $data['caregivers']  ?? null,
            $data['groups']  ?? null,
            $data['awards']  ?? null,
            $data['datasharing']  ?? null,
        );
    }

    public function toArray(): array
    {
        return [
            'student_id' => $this->student_id,
            'uuid' => $this->uuid,
            'role' => $this->role,
            'schoolindex' => $this->schoolindex,
            'nsn' => $this->nsn,
            'created' => $this->created,
            'uniqueid' => $this->uniqueid,
            'accountdisabled' => $this->accountdisabled ?? false,
            'signedagreement' => $this->signedagreement ?? false,
            'byodinfo' => $this->byodinfo,
            'username' => $this->username,
            'firstname' => $this->firstname,
            'lastname' => $this->lastname,
            'gender' => $this->gender,
            'genderpreferred' => $this->genderpreferred,
            'gendercode' => $this->gendercode,
            'ethnicityL1' => $this->ethnicityL1,
            'ethnicityL2' => $this->ethnicityL2,
            'ethnicity' => $this->ethnicity,
            'iwi' => $this->iwi,
            'siblinglink' => $this->siblinglink,
            'boarder' => $this->boarder ?? false,
            'datebirth' => $this->datebirth,
            'yearlevel' => $this->yearlevel,
            'fundinglevel' => $this->fundinglevel,
            'moetype' => $this->moetype,
            'ece' => $this->ece,
            'ors' => $this->ors,
            'esol' => $this->esol ?? false,
            'languagespoken' => $this->languagespoken,
            'tutor' => $this->tutor,
            'house' => $this->house,
            'whanau' => $this->whanau,
            'timetabletop' => $this->timetabletop,
            'timetablebottom' => $this->timetablebottom,
            'photocoperid' => $this->photocoperid,
            'startschooldate' => $this->startschooldate,
            'startingdate' => $this->startingdate,
            'leavingdate' => $this->leavingdate,
            'leavingreason' => $this->leavingreason,
            'leavingactivity' => $this->leavingactivity,
            'leavingschools' => $this->leavingschools,
            'email' => $this->email,
            'mobile' => $this->mobile,
            'networkaccess' => $this->networkaccess ?? true,
            'althomedrive' => $this->althomedrive,
            'altdescription' => $this->altdescription,
            'residence' => $this->residence,
            'caregivers' => $this->caregivers,
            'groups' => $this->groups,
            'awards' => $this->awards,
            'datasharing' => $this->datasharing,
        ];
    }
}
